https://test.ru/api/users/currentuser

###
http://dallasstudio.ru/api/tickets

###
https://test.ru/api/users?groups=teacher

###
POST https://test.ru/api/users/signup
Content-Type: application/json

{
    "name": "Petrov Pavel",
    "email": "test2@test.ru",
    "password": "1212",
    "admin": true
}

###
POST https://test.ru/api/users/signin
Content-Type: application/json

{
    "email":"test@test.ru",
    "password":"1212"
}

###
POST test.ru/api/tickets
Content-Type: application/json

{"title":"test", "price": 3}

###
GET test.ru/api/tickets
Content-Type: application/json

###
GET test.ru/api/orders

###
POST test.ru/api/orders
Content-Type: application/json

{"ticketId":"61fc74b0d8a6f58679c56e49"}


###
POST test.ru/api/payments
Content-Type: application/json

{"orderId":"61fc74c2e87e2288865eaa35"}


###
GET test.ru/api/payments/61fc74c2e87e2288865eaa35
Content-Type: application/json

###
GET test.ru/api/payments
Content-Type: application/json

###
POST test.ru/api/orders/trial
Content-Type: application/json

{"name":"Pavel", "phone": "+79231453456"}

###
GET test.ru/api/orders/trial?skip=0
Content-Type: application/json