POST https://api.yookassa.ru/v3/payments
Content-Type: application/json
Authorization: Basic ODQxNzE4OmxpdmVfaHQ5ZHZ4MU54XzRwOEJPaTJHOGx1blU2ZE5mSll2MUJvbTRib2ZlQzJOOA==
Idempotence-Key: 22311

{
    "amount": {"value": "2.00","currency":"RUB"},
    "confirmation": {"type": "embedded "},
    "capture": true
}

###
GET https://api.yookassa.ru/v3/payments/2973ffbc-000f-5000-8000-123e7ad49acf
Content-Type: application/json
Authorization: Basic ODQxNzE4OmxpdmVfaHQ5ZHZ4MU54XzRwOEJPaTJHOGx1blU2ZE5mSll2MUJvbTRib2ZlQzJOOA==

###
GET https://api.yookassa.ru/v3/payments/?limit=5
Content-Type: application/json
Authorization: Basic ODQxNzE4OmxpdmVfaHQ5ZHZ4MU54XzRwOEJPaTJHOGx1blU2ZE5mSll2MUJvbTRib2ZlQzJOOA==