POST https://api.yookassa.ru/v3/payments
Content-Type: application/json
Authorization: Basic ODQxNzE4OmxpdmVfaHQ5ZHZ4MU54XzRwOEJPaTJHOGx1blU2ZE5mSll2MUJvbTRib2ZlQzJOOA==
Idempotence-Key: 223

{"amount":
    {"value": "2.00","currency":"RUB"},
    "payment_method_data": {"type": "bank_card"},
    "confirmation": {"type": "redirect","return_url": "test"},
    "capture": true
}

29721f74-000f-5000-9000-1e81ddd9dd87

###
GET https://api.yookassa.ru/v3/payments/2972516f-000f-5000-a000-1c9811248687
Content-Type: application/json
Authorization: Basic ODQxNzE4OmxpdmVfaHQ5ZHZ4MU54XzRwOEJPaTJHOGx1blU2ZE5mSll2MUJvbTRib2ZlQzJOOA==

###
GET https://api.yookassa.ru/v3/payments/?limit=5
Content-Type: application/json
Authorization: Basic ODQxNzE4OmxpdmVfaHQ5ZHZ4MU54XzRwOEJPaTJHOGx1blU2ZE5mSll2MUJvbTRib2ZlQzJOOA==